"use client";

import { useTranslations } from "next-intl";
import WeekSelector from "@/components/timesheets/WeekSelector";
import type { ApprovalStatus, WeekRange } from "@/lib/types/timesheet";

export type StatusFilter = "all" | ApprovalStatus;
type Props = { weeks: WeekRange[]; week: string; employee: string; locationName: string; status: StatusFilter; search: string; employees: string[]; locations: string[]; onWeek: (value: string) => void; onEmployee: (value: string) => void; onLocation: (value: string) => void; onStatus: (value: StatusFilter) => void; onSearch: (value: string) => void; onClear: () => void; hasFilters: boolean };
const control = "mt-2 min-h-11 w-full rounded-lg border border-white/10 bg-surface px-3 text-sm text-ink outline-none focus:border-brand focus:ring-2 focus:ring-brand/20";
export default function TimesheetFilters(props: Props) { const t = useTranslations("timesheets"); return <section aria-label={t("filtersAriaLabel")} className="grid gap-3 rounded-2xl border border-white/10 bg-surface/60 p-4 sm:grid-cols-2 xl:grid-cols-[1.2fr_1fr_1fr_1fr_1.2fr_auto] xl:items-end"><WeekSelector weeks={props.weeks} value={props.week} onChange={props.onWeek} /><div><label htmlFor="timesheet-employee" className="text-xs font-medium text-ink-muted">{t("employee")}</label><select id="timesheet-employee" value={props.employee} onChange={(event) => props.onEmployee(event.target.value)} className={control}><option value="all">{t("allEmployees")}</option>{props.employees.map((employee) => <option key={employee} value={employee}>{employee}</option>)}</select></div><div><label htmlFor="timesheet-location" className="text-xs font-medium text-ink-muted">{t("location")}</label><select id="timesheet-location" value={props.locationName} onChange={(event) => props.onLocation(event.target.value)} className={control}><option value="all">{t("allLocations")}</option>{props.locations.map((project) => <option key={project} value={project}>{project}</option>)}</select></div><div><label htmlFor="timesheet-status" className="text-xs font-medium text-ink-muted">{t("status")}</label><select id="timesheet-status" value={props.status} onChange={(event) => props.onStatus(event.target.value as StatusFilter)} className={control}><option value="all">{t("allStatuses")}</option><option value="draft">{t("statusDraft")}</option><option value="submitted">{t("statusSubmitted")}</option><option value="approved">{t("statusApproved")}</option><option value="rejected">{t("statusRejected")}</option></select></div><div><label htmlFor="timesheet-search" className="text-xs font-medium text-ink-muted">{t("search")}</label><input id="timesheet-search" type="search" value={props.search} onChange={(event) => props.onSearch(event.target.value)} placeholder={t("searchPlaceholder")} className={control} /></div><button type="button" onClick={props.onClear} disabled={!props.hasFilters} className="min-h-11 rounded-lg px-4 text-sm font-semibold text-ink-muted transition hover:bg-white/5 hover:text-ink focus-visible:outline-2 focus-visible:outline-brand disabled:cursor-not-allowed disabled:opacity-40">{t("clearFilters")}</button></section>; }
