"use client";

import { useTranslations } from "next-intl";
import ApprovalStatusBadge from "@/components/timesheets/ApprovalStatusBadge";
import type { TimesheetEntry } from "@/lib/types/timesheet";

export default function TimesheetTable({ entries, onEdit }: { entries: TimesheetEntry[]; onEdit: (entry: TimesheetEntry) => void }) {
  const t = useTranslations("timesheets");
  const columns: [string, string][] = [[t("columnDate"), "w-[10%]"], [t("columnProject"), "w-[15%]"], [t("columnTask"), "w-[15%]"], [t("columnStart"), "w-[7%]"], [t("columnEnd"), "w-[7%]"], [t("columnBreak"), "w-[7%]"], [t("columnWorked"), "w-[8%]"], [t("columnStatus"), "w-[11%]"], [t("columnNotes"), "w-[15%]"], ["", "w-[5%]"]];
  return <div className="hidden overflow-hidden rounded-2xl border border-white/10 bg-[#161A34] md:block"><table className="w-full table-fixed text-left text-sm"><caption className="sr-only">{t("tableCaption")}</caption><thead className="bg-white/[0.03] text-xs uppercase tracking-wide text-[#9CA3AF]"><tr>{columns.map(([label, width]) => <th key={label || "actions"} scope="col" className={`${width} px-3 py-4 font-semibold`}>{label}<span className="sr-only">{label ? "" : t("actions")}</span></th>)}</tr></thead><tbody className="divide-y divide-white/10">{entries.map((entry) => <tr key={entry.id} className="transition hover:bg-white/[0.025]"><td className="px-3 py-4 text-[#D1D5DB]">{entry.date}</td><td className="truncate px-3 py-4 font-medium text-[#E5E7EB]" title={entry.project}>{entry.project}</td><td className="truncate px-3 py-4 text-[#D1D5DB]" title={entry.task}>{entry.task}</td><td className="px-3 py-4 text-[#D1D5DB]">{entry.startTime}</td><td className="px-3 py-4 text-[#D1D5DB]">{entry.endTime}</td><td className="px-3 py-4 text-[#D1D5DB]">{entry.breakMinutes}m</td><td className="px-3 py-4 font-semibold text-[#4ADE80]">{Math.floor(entry.workedMinutes / 60)}h {entry.workedMinutes % 60}m</td><td className="px-3 py-4"><ApprovalStatusBadge status={entry.status} /></td><td className="truncate px-3 py-4 text-[#9CA3AF]" title={entry.notes}>{entry.notes}</td><td className="px-3 py-4">{/* No pencil where the database will refuse: approved hours are immutable, and a submitted week is the reviewer's to correct. */}{entry.canEdit ? <button type="button" onClick={() => onEdit(entry)} aria-label={t("editEntryAria", { project: entry.project, date: entry.date })} aria-haspopup="dialog" className="flex min-h-11 min-w-11 items-center justify-center rounded-lg text-[#9CA3AF] hover:bg-white/5 hover:text-[#E5E7EB] focus-visible:outline-2 focus-visible:outline-[#22C55E]">✎</button> : null}</td></tr>)}</tbody></table></div>;
}
