"use client";
import type { ReactNode } from "react"; import Link from "next/link"; import { componentClasses } from "@/src/design-system";
export function Breadcrumb({ items }: { items: { label: string; href?: string }[] }) { return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap items-center gap-2 text-sm">{items.map((item,index)=><li key={`${item.label}-${index}`} className="flex items-center gap-2">{index ? <span aria-hidden="true" className="text-ink-subtle">/</span> : null}{item.href ? <Link href={item.href} className={`min-h-11 content-center text-ink-muted hover:text-ink ${componentClasses.focus}`}>{item.label}</Link> : <span aria-current="page" className="text-ink">{item.label}</span>}</li>)}</ol></nav>; }
export function NavigationItem({ href, label, icon, active }: { href: string; label: string; icon?: ReactNode; active?: boolean }) { return <Link href={href} aria-current={active ? "page" : undefined} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-medium ${componentClasses.focus} ${active ? "bg-brand/10 text-brand" : "text-ink-soft hover:bg-white/5"}`}>{icon}{label}</Link>; }
export const SidebarItem = NavigationItem; export const MenuItem = NavigationItem;
export function Dropdown({ label, children }: { label: string; children: ReactNode }) { return <details className="relative"><summary className={`flex min-h-11 cursor-pointer list-none items-center rounded-lg px-3 text-sm text-ink ${componentClasses.focus}`}>{label}</summary><div className="absolute right-0 z-20 mt-2 min-w-48 rounded-xl border border-white/10 bg-surface p-2 shadow-xl">{children}</div></details>; }
export function Tabs({ items, activeId, onChange }: { items: { id: string; label: string }[]; activeId: string; onChange: (id:string)=>void }) { return <div role="tablist" className="flex gap-1 overflow-x-auto border-b border-white/10">{items.map((item)=><button key={item.id} type="button" role="tab" aria-selected={item.id===activeId} onClick={()=>onChange(item.id)} className={`min-h-11 whitespace-nowrap border-b-2 px-4 text-sm font-semibold ${componentClasses.focus} ${item.id===activeId ? "border-brand text-brand" : "border-transparent text-ink-muted"}`}>{item.label}</button>)}</div>; }
export function SegmentedControl(props: Parameters<typeof Tabs>[0]) { return <div className="rounded-xl border border-white/10 p-1"><Tabs {...props}/></div>; }
export function Pagination({ page, pages, onChange }: { page:number; pages:number; onChange:(page:number)=>void }) { return <nav aria-label="Pagination" className="flex items-center justify-between gap-3"><button type="button" disabled={page<=1} onClick={()=>onChange(page-1)} className={`min-h-11 rounded-lg px-4 text-sm text-ink disabled:opacity-40 ${componentClasses.focus}`}>Previous</button><span className="text-sm text-ink-muted">Page {page} of {pages}</span><button type="button" disabled={page>=pages} onClick={()=>onChange(page+1)} className={`min-h-11 rounded-lg px-4 text-sm text-ink disabled:opacity-40 ${componentClasses.focus}`}>Next</button></nav>; }
export function CommandPalette({ open, label="Command palette", children }: { open:boolean; label?:string; children:ReactNode }) { return open ? <div role="dialog" aria-modal="true" aria-label={label} className="fixed inset-x-4 top-[10dvh] z-50 mx-auto max-w-xl rounded-2xl border border-white/10 bg-surface p-4 shadow-2xl">{children}</div> : null; }
