"use client";
import { useEffect, useRef, type ReactNode } from "react"; import { Button } from "@/src/components/ui";
export function Alert({ title, children, tone = "info" }: { title: string; children: ReactNode; tone?: "info" | "success" | "warning" | "danger" }) { const tones = { info: "border-blue-400/30 bg-blue-400/10", success: "border-green-400/30 bg-green-400/10", warning: "border-amber-400/30 bg-amber-400/10", danger: "border-red-400/30 bg-red-400/10" }; return <div role="alert" className={`rounded-xl border p-4 ${tones[tone]}`}><h3 className="font-semibold text-ink">{title}</h3><div className="mt-1 text-sm text-ink-soft">{children}</div></div>; }
export const Banner = Alert; export const Toast = Alert;
export function Spinner({ label = "Loading" }: { label?: string }) { return <span role="status" aria-label={label} className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-brand border-r-transparent"/>; }
export function LoadingOverlay({ visible, label }: { visible: boolean; label?: string }) { return visible ? <div className="absolute inset-0 z-40 flex items-center justify-center rounded-inherit bg-surface-alt/80"><Spinner label={label}/></div> : null; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { if (!open) return; closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className="max-h-[90dvh] w-full overflow-y-auto rounded-t-2xl border border-white/10 bg-surface p-5 sm:max-w-lg sm:rounded-2xl"><div className="flex items-center justify-between gap-4"><h2 id="modal-title" className="text-lg font-semibold text-ink">{title}</h2><Button ref={closeRef} variant="ghost" onClick={onClose} aria-label="Close dialog">×</Button></div><div className="mt-5">{children}</div></section></div>; }
export function Drawer({ open, title, children, onClose }: Parameters<typeof Modal>[0]) { if (!open) return null; return <div className="fixed inset-0 z-40 bg-black/60" role="presentation"><aside role="dialog" aria-modal="true" aria-label={title} className="ml-auto h-full w-[min(24rem,100%)] overflow-y-auto border-l border-white/10 bg-surface p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-ink">{title}</h2><Button variant="ghost" onClick={onClose} aria-label="Close drawer">×</Button></div><div className="mt-5">{children}</div></aside></div>; }
export function ConfirmationDialog({ open, title, description, confirmLabel = "Confirm", onConfirm, onClose }: { open: boolean; title: string; description: string; confirmLabel?: string; onConfirm: () => void; onClose: () => void }) { return <Modal open={open} title={title} onClose={onClose}><p className="text-sm text-ink-muted">{description}</p><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></Modal>; }
