import type { ReactNode } from "react"; import { componentClasses } from "@/src/design-system";
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "danger" | "info" }) { const tones = { neutral: "bg-white/10 text-ink-soft", success: "bg-green-400/10 text-green-300", warning: "bg-amber-400/10 text-amber-300", danger: "bg-red-400/10 text-red-300", info: "bg-blue-400/10 text-blue-300" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>; }
export const Tag = Badge; export const Chip = Badge; export const StatusBadge = Badge;
export function Avatar({ name, src, size = "md" }: { name: string; src?: string; size?: "sm" | "md" | "lg" }) { const sizes = { sm: "h-8 w-8 text-xs", md: "h-10 w-10 text-sm", lg: "h-12 w-12 text-base" }; const initials = name.split(" ").map((part) => part[0]).slice(0,2).join(""); return <span role="img" aria-label={name} className={`${sizes[size]} inline-flex items-center justify-center rounded-full bg-cover bg-center bg-no-repeat font-bold text-brand ${src ? "" : "bg-brand/10"}`} style={src ? { backgroundImage: `url(${JSON.stringify(src).slice(1,-1)})` } : undefined}>{src ? null : initials}</span>; }
export function AvatarGroup({ people }: { people: { name: string; src?: string }[] }) { return <ul className="flex -space-x-2" aria-label={`${people.length} people`}>{people.map((person) => <li key={person.name} className="rounded-full ring-2 ring-surface"><Avatar {...person}/></li>)}</ul>; }
export function ProgressBar({ value, label }: { value: number; label: string }) { const safe = Math.max(0, Math.min(100, value)); return <div><div className="mb-2 flex justify-between text-xs text-ink-muted"><span>{label}</span><span>{safe}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10" role="progressbar" aria-label={label} aria-valuenow={safe} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-brand" style={{ width: `${safe}%` }}/></div></div>; }
export function MetricCard({ label, value, detail }: { label: string; value: ReactNode; detail?: string }) { return <article className={`${componentClasses.surface} p-5`}><p className="text-sm text-ink-muted">{label}</p><p className="mt-2 text-2xl font-bold text-ink">{value}</p>{detail ? <p className="mt-2 text-xs text-ink-muted">{detail}</p> : null}</article>; }
export const StatCard = MetricCard;
export function EmptyState({ title, description, action, icon }: { title: string; description: string; action?: ReactNode; icon?: ReactNode }) { return <div className="rounded-2xl border border-dashed border-white/15 bg-surface p-8 text-center">{icon}<h3 className="font-semibold text-ink">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm text-ink-muted">{description}</p>{action ? <div className="mt-5">{action}</div> : null}</div>; }
export function Divider() { return <hr className="border-0 border-t border-white/10"/>; }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="group relative inline-flex" tabIndex={0} aria-describedby={`tip-${label.replaceAll(" ", "-")}`}><span>{children}</span><span role="tooltip" id={`tip-${label.replaceAll(" ", "-")}`} className="pointer-events-none absolute bottom-full left-1/2 z-20 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-black px-2 py-1 text-xs text-white group-hover:block group-focus:block">{label}</span></span>; }
export function Popover({ label, children }: { label: string; children: ReactNode }) { return <details className="relative"><summary className="flex min-h-11 cursor-pointer list-none items-center rounded-lg px-3 text-sm text-ink focus-visible:outline-2 focus-visible:outline-brand">{label}</summary><div className="absolute right-0 z-20 mt-2 min-w-56 rounded-xl border border-white/10 bg-surface p-4 shadow-xl">{children}</div></details>; }
export function Accordion({ items }: { items: { id: string; title: string; content: ReactNode }[] }) { return <div className="divide-y divide-white/10 rounded-xl border border-white/10">{items.map((item) => <details key={item.id} className="group p-4"><summary className="flex min-h-11 cursor-pointer items-center font-medium text-ink focus-visible:outline-2 focus-visible:outline-brand">{item.title}</summary><div className="pb-2 text-sm leading-6 text-ink-muted">{item.content}</div></details>)}</div>; }
