"use client";
import { useMemo, useState } from "react"; import { useTranslations } from "next-intl"; import Link from "next/link"; import type { Client, Project } from "@/lib/types/project"; import EmptyProjectsState from "./EmptyProjectsState"; import ProjectCard from "./ProjectCard"; import ProjectFilters, { type ProjectFiltersValue } from "./ProjectFilters"; import ProjectStatusBadge from "./ProjectStatusBadge";
const initial: ProjectFiltersValue = { search: "", client: "all", status: "all", priority: "all" };
export default function ProjectsTable({ projects, clients }: { projects: Project[]; clients: Client[] }) {
  const t = useTranslations("projects");
  const [filters, setFilters] = useState(initial); const clientById = useMemo(() => new Map(clients.map((client) => [client.id, client])), [clients]); const filtered = useMemo(() => projects.filter((project) => { const client = project.clientId ? clientById.get(project.clientId) : undefined; const query = filters.search.trim().toLowerCase(); return (!query || `${project.name} ${client?.companyName ?? ""}`.toLowerCase().includes(query)) && (filters.client === "all" || project.clientId === filters.client) && (filters.status === "all" || project.status === filters.status) && (filters.priority === "all" || project.priority === filters.priority); }), [clientById, filters, projects]); const hasFilters = JSON.stringify(filters) !== JSON.stringify(initial);
  const columns = [t("columnProject"), t("columnClient"), t("columnStatus"), t("columnPriority"), t("columnHours"), t("columnProgress"), t("columnStartDate")];
  return <div className="mt-6"><ProjectFilters value={filters} clients={clients} onChange={setFilters} onClear={() => setFilters(initial)} hasFilters={hasFilters}/><p className="mt-4 text-sm text-[#9CA3AF]" aria-live="polite">{t("showingCount", { shown: filtered.length, total: projects.length })}</p>{filtered.length === 0 ? <div className="mt-4"><EmptyProjectsState filtered={hasFilters}/></div> : <><div className="mt-4 hidden overflow-hidden rounded-2xl border border-white/10 bg-[#161A34] xl:block"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-white/10 bg-[#111827]/60 text-xs uppercase text-[#9CA3AF]"><tr>{columns.map((heading) => <th key={heading} scope="col" className="px-4 py-4 font-medium">{heading}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{filtered.map((project) => { // Internal work has no client; the cell says so rather than crashing.
    const client = project.clientId ? clientById.get(project.clientId) : undefined; const progress = Math.min(100, Math.round(project.workedHours / project.estimatedHours * 100)); return <tr key={project.id} className="hover:bg-white/[0.03]"><th scope="row" className="px-4 py-4"><Link href={`/dashboard/projects/${project.id}`} className="font-semibold text-[#E5E7EB] focus-visible:outline-2 focus-visible:outline-[#22C55E]">{project.name}</Link></th><td className="px-4 py-4 text-[#D1D5DB]">{client?.companyName ?? t("noClient")}</td><td className="px-4 py-4"><ProjectStatusBadge status={project.status}/></td><td className="px-4 py-4 capitalize text-[#D1D5DB]">{t(`priority${project.priority.charAt(0).toUpperCase()}${project.priority.slice(1)}`)}</td><td className="px-4 py-4 text-[#D1D5DB]">{project.workedHours} / {project.estimatedHours}</td><td className="px-4 py-4"><span className="sr-only">{t("percentComplete", { percent: progress })}</span><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#22C55E]" style={{ width: `${progress}%` }}/></div></td><td className="px-4 py-4 text-[#9CA3AF]">{project.startDate}</td></tr>; })}</tbody></table></div><ul className="mt-4 grid gap-4 sm:grid-cols-2 xl:hidden">{filtered.map((project) => <ProjectCard key={project.id} project={project} client={project.clientId ? clientById.get(project.clientId) : undefined}/>)}</ul></>}</div>;
}
