"use client";
import { useActionState } from "react"; import { useTranslations } from "next-intl"; import Link from "next/link"; import type { ClientOption } from "@/src/features/sites/types"; import ClientPicker from "@/components/sites/ClientPicker"; import { createProjectAction, type CreateProjectState } from "@/src/features/projects/actions";
const field = "mt-2 min-h-12 w-full rounded-lg border border-white/10 bg-[#111827] px-4 text-base text-[#E5E7EB] outline-none focus:border-[#22C55E] focus:ring-2 focus:ring-[#22C55E]/20 user-invalid:border-red-400";
export default function ProjectForm({ clients }: { clients: ClientOption[] }) {
  const t = useTranslations("projects");
  const [state, formAction] = useActionState(createProjectAction, { status: "idle", message: "" } as CreateProjectState);
  const statusOptions = [["planning", t("statusPlanning")], ["active", t("statusActive")], ["paused", t("statusPaused")], ["completed", t("statusCompleted")], ["cancelled", t("statusCancelled")]];
  const priorityOptions = [["low", t("priorityLow")], ["medium", t("priorityMedium")], ["high", t("priorityHigh")], ["critical", t("priorityCritical")]];
  return <form action={formAction} className="rounded-2xl border border-white/10 bg-[#161A34] p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field id="project-name" label={t("projectName")}><input id="project-name" name="name" required minLength={2} className={field}/></Field><ClientPicker clients={clients} /><Field id="status" label={t("status")}><select id="status" name="status" defaultValue="planning" required className={field}>{statusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field id="priority" label={t("priority")}><select id="priority" name="priority" defaultValue="medium" required className={field}>{priorityOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>{[["estimated-hours", t("estimatedHours"), "number"], ["budget", t("budget"), "number"], ["start-date", t("startDate"), "date"], ["end-date", t("endDate"), "date"]].map(([id, label, type]) => <Field key={id} id={id} label={label}><input id={id} name={id} type={type} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} required className={field}/></Field>)}<div className="sm:col-span-2"><Field id="description" label={t("description")}><textarea id="description" name="description" required rows={5} className={`${field} py-3`}/></Field></div></div>{state.status === "error" ? <p role="alert" className="mt-6 rounded-lg bg-red-400/10 p-4 text-sm leading-6 text-red-300">{state.message}</p> : null}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link href="/dashboard/projects" className="flex min-h-11 items-center justify-center rounded-lg border border-white/15 px-5 text-sm font-semibold text-[#E5E7EB] focus-visible:outline-2 focus-visible:outline-[#22C55E]">{t("cancel")}</Link><button type="submit" className="min-h-11 rounded-lg bg-[#22C55E] px-5 text-sm font-semibold text-[#07110B] hover:bg-[#16A34A] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#22C55E]">{t("createProject")}</button></div></form>;
}
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div><label htmlFor={id} className="text-sm font-medium text-[#E5E7EB]">{label}</label>{children}</div>; }
