"use client";
import { forwardRef, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react"; import { componentClasses } from "@/src/design-system";
export interface FieldShellProps { id: string; label: string; hint?: string; error?: string; children: ReactNode }
export function FieldShell({ id, label, hint, error, children }: FieldShellProps) { const messageId = `${id}-message`; return <div><label htmlFor={id} className="text-sm font-medium text-ink">{label}</label>{children}{hint || error ? <p id={messageId} className={`mt-1 text-xs ${error ? "text-red-300" : "text-ink-muted"}`} role={error ? "alert" : undefined}>{error ?? hint}</p> : null}</div>; }
export interface InputProps extends InputHTMLAttributes<HTMLInputElement> { label: string; error?: string; hint?: string }
export const Input = forwardRef<HTMLInputElement, InputProps>(function Input({ id, label, error, hint, className = "", ...props }, ref) { const inputId = id ?? props.name ?? "field"; return <FieldShell id={inputId} label={label} hint={hint} error={error}><input ref={ref} id={inputId} aria-invalid={Boolean(error)} aria-describedby={error || hint ? `${inputId}-message` : undefined} className={`mt-2 w-full ${componentClasses.control} ${className}`} {...props}/></FieldShell>; });
export const TextInput = Input; export const EmailInput = (props: InputProps) => <Input type="email" inputMode="email" autoComplete="email" {...props}/>; export const PasswordInput = (props: InputProps) => <Input type="password" autoComplete="current-password" {...props}/>; export const SearchInput = (props: InputProps) => <Input type="search" {...props}/>; export const PhoneInput = (props: InputProps) => <Input type="tel" inputMode="tel" autoComplete="tel" {...props}/>; export const NumberInput = (props: InputProps) => <Input type="number" inputMode="decimal" {...props}/>; export const DateInput = (props: InputProps) => <Input type="date" {...props}/>; export const TimeInput = (props: InputProps) => <Input type="time" {...props}/>; export const DateTimeInput = (props: InputProps) => <Input type="datetime-local" {...props}/>;
export function Textarea({ label, error, hint, id, className = "", ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string; error?: string; hint?: string }) { const inputId = id ?? props.name ?? "textarea"; return <FieldShell id={inputId} label={label} hint={hint} error={error}><textarea id={inputId} aria-invalid={Boolean(error)} className={`mt-2 min-h-28 w-full py-3 ${componentClasses.control} ${className}`} {...props}/></FieldShell>; }
export function Select({ label, options, error, id, className = "", ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; options: { value: string; label: string }[]; error?: string }) { const inputId = id ?? props.name ?? "select"; return <FieldShell id={inputId} label={label} error={error}><select id={inputId} aria-invalid={Boolean(error)} className={`mt-2 w-full ${componentClasses.control} ${className}`} {...props}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></FieldShell>; }
export function Choice({ type, label, ...props }: InputHTMLAttributes<HTMLInputElement> & { type: "checkbox" | "radio"; label: string }) { return <label className="flex min-h-11 cursor-pointer items-center gap-3 text-sm text-ink"><input type={type} className="h-5 w-5 accent-brand focus-visible:outline-2 focus-visible:outline-brand-bright" {...props}/>{label}</label>; }
export const Checkbox = (props: Omit<Parameters<typeof Choice>[0], "type">) => <Choice type="checkbox" {...props}/>; export const Radio = (props: Omit<Parameters<typeof Choice>[0], "type">) => <Choice type="radio" {...props}/>;
export function Switch({ label, checked, onChange, disabled }: { label: string; checked: boolean; onChange: (checked: boolean) => void; disabled?: boolean }) { return <label className="flex min-h-11 cursor-pointer items-center gap-3 text-sm text-ink"><input type="checkbox" role="switch" checked={checked} onChange={(event) => onChange(event.target.checked)} disabled={disabled} className="peer sr-only"/><span className="relative h-6 w-11 rounded-full bg-[#374151] after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-white after:transition peer-checked:bg-brand peer-checked:after:translate-x-5 peer-focus-visible:ring-2 peer-focus-visible:ring-brand"/>{label}</label>; }
export function MultiSelect(props: Parameters<typeof Select>[0]) { return <Select multiple {...props}/>; } export function Autocomplete({ suggestions, ...props }: InputProps & { suggestions: string[] }) { const listId = `${props.id ?? props.name}-options`; return <><Input list={listId} {...props}/><datalist id={listId}>{suggestions.map((item) => <option key={item} value={item}/>)}</datalist></>; }
